services:
  - type: web
    name: school-application-system
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm ci
      npm run build
    startCommand: |
      php artisan migrate --force
      php artisan storage:link
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://school-application-system.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stack
      - key: MAIL_MAILER
        value: log
