version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_NAME=School Application System
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:ko3dW4IMQqhA5Y8RiFZqref/ahOasL6jbZLOKMCO9kk=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=database/database.sqlite
      - CACHE_STORE=database
      - SESSION_DRIVER=database
      - QUEUE_CONNECTION=database
      - LOG_CHANNEL=stack
      - LOG_LEVEL=error
      - MAIL_MAILER=log
      - MAIL_FROM_ADDRESS=noreply@school.com
      - MAIL_FROM_NAME=School Application System
    volumes:
      - ./database:/var/www/html/database
      - ./storage:/var/www/html/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
